### ISSUE TITLE
full usage instructions

### ISSUE THREAD

**Issue by sosso** [mapbox/osrm-isochrone#14]
Can you, from `nvm install`, provide a full usage recipe please?  Having a whale of a time getting this running.

**Comment by agponte** [comment]
@sosso did you ever get this going?

I noticed recent activity getting this into OSRM at https://github.com/Project-OSRM/osrm-backend/pull/2477

**Comment by sosso** [comment]
I never did get it working. That PR is obviously very interesting; is there
anything I can do to help out?
On Aug 29, 2016 2:36 PM, "Al Ponte" <notifications@github.com> wrote:

> <https://github.com/sosso>

> @sosso <https://github.com/sosso> did you ever get this going?
>
> I noticed recent activity getting this into OSRM at
Project-OSRM/osrm-backend#2477
<https://github.com/Project-OSRM/osrm-backend/pull/2477>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
<https://github.com/mapbox/osrm-isochrone/issues/14#issuecomment-243213819>,
or mute the thread

**Comment by agponte** [comment]
I don't know anything about the PR but am trying hard to get this isochrone add-on running...can you email me directly at al -at- maplarge -dot- com maybe we can help each other out here than post back the fix.

**Comment by agponte** [comment]
To get this working I had to make some local updates to work against the latest osrm backend and it took most of today.

**Comment by TheMarex** [comment]
Should be in a much better state now. Sorry that this project went overlooked for so long.
