### ISSUE TITLE
lines or polygons

### ISSUE THREAD

**Issue by morganherlocker** [mapbox/osrm-isochrone#2]
Results should be geojson. Should they be linestrings or polygons? If they are polygons, it will be easiest to have them stacked.

**Comment by stvno** [comment]
Polygons are messy to create, but useful for visualization: for instance the middle of the Sahara is more difficult to reach than the coast http://stvno.github.io/page/bartholomap/view.html#3.9/21.64/16.29 which can be neatly visualized with holes in polygons and nice colors, but are difficult to decipher from lines
