### ISSUE TITLE
 Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.14.3/Release/node-v51-linux-x64.tar.gz

### ISSUE THREAD

**Issue by geography** [mapbox/osrm-isochrone#27]
Hi all,

when I try to install it, gives me this error:

npm WARN deprecated @turf/inside@3.14.0: Module has been renamed to @turf/boolean-point-in-polygon

> osrm@5.14.3 install /usr/lib/node_modules/osrm-isochrone/node_modules/osrm
> node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.14.3/Release/node-v51-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/osrm-isochrone/node_modules/osrm/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:191:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/usr/lib/node_modules/osrm-isochrone/node_modules/osrm/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:191:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:411:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Linux 4.4.0-51-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/osrm-isochrone/node_modules/osrm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /usr/lib/node_modules/osrm-isochrone/node_modules/osrm
node-pre-gyp ERR! node -v v7.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.14.3/Release/node-v51-linux-x64.tar.gz
/usr/lib/node_modules/osrm-isochrone/node_modules/osrm/build /usr/lib/node_modules/osrm-isochrone/node_modules/osrm
CMake Error: The source directory "/usr/lib/node_modules/osrm-isochrone/node_modules/osrm" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
/usr/lib
└── (empty)

npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "osrm-isochrone"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! osrm@5.14.3 install: `node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osrm@5.14.3 install script 'node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the osrm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs osrm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls osrm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2018-01-05T11_10_07_423Z-debug.log

Do you have any suggestion?

**Comment by daniel-j-h** [comment]
> node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.14.3/Release/node-v51-linux-x64.tar.gz

Node.js ABI v51 is Node.js 7.

osrm-backend only provides pre-built Node.js binaries for Node.js LTS 4, 6, 8.

Either use a Node.js LTS version or build osrm-backend's node-osrm module from source.

https://nodejs.org/en/download/releases/

**Comment by geography** [comment]
Thanks Daniel,

after: 
1) nvm install 7 
2) nvm use 7
3) npm install -g isochrone
the results is:
npm WARN deprecated @turf/inside@4.7.3: Module has been renamed to @turf/boolean-point-in-polygon
npm WARN deprecated geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead
/root/.nvm/versions/node/v7.10.1/lib
├─┬ isochrone@2.0.1
│ ├─┬ @turf/bbox@4.5.2
│ │ └── @turf/meta@4.7.4
│ ├─┬ @turf/destination@4.5.2
│ │ └── @turf/invariant@4.7.3
│ ├── @turf/helpers@4.5.2
│ ├─┬ @turf/point-grid@4.5.2
│ │ ├─┬ @turf/distance@4.7.3
│ │ │ └── @turf/helpers@4.7.3
│ │ └── @turf/inside@4.7.3
│ ├─┬ concaveman@1.1.1
│ │ ├── monotone-convex-hull-2d@1.0.1
│ │ ├── point-in-polygon@1.0.1
│ │ ├─┬ rbush@2.0.2
│ │ │ └── quickselect@1.0.1
│ │ ├─┬ robust-orientation@1.1.3
│ │ │ ├─┬ robust-scale@1.0.2
│ │ │ │ └── two-sum@1.0.0
│ │ │ ├── robust-subtract@1.0.0
│ │ │ ├── robust-sum@1.0.0
│ │ │ └── two-product@1.0.2
│ │ └── tinyqueue@1.2.3
│ ├─┬ geojson-rewind@0.2.0
│ │ ├─┬ concat-stream@1.2.1
│ │ │ └─┬ bops@0.0.6
│ │ │   ├── base64-js@0.0.2
│ │ │   └── to-utf8@0.0.1
│ │ ├─┬ geojson-area@0.1.0
│ │ │ └── wgs84@0.0.0
│ │ └── minimist@0.0.5
│ └─┬ turf-deintersect@1.0.1
│   └─┬ @turf/difference@4.3.0
│     ├─┬ @turf/area@4.7.3
│     │ └── @mapbox/geojson-area@0.2.2
│     └── jsts@1.5.0
└── UNMET PEER DEPENDENCY osrm@^5.0

npm WARN isochrone@2.0.1 requires a peer of osrm@^5.0 but none was installed.
root@geoboundless:/home/ubuntu# sudo npm install -g isochrone
npm WARN deprecated @turf/inside@4.7.3: Module has been renamed to @turf/boolean-point-in-polygon
npm WARN deprecated geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead
/usr/lib
├── isochrone@2.0.1
└── UNMET PEER DEPENDENCY osrm@^5.0

npm WARN isochrone@2.0.1 requires a peer of osrm@^5.0 but none was installed.

Thanks again.

**Comment by daniel-j-h** [comment]
> nvm install 7
> nvm use 7 

osrm-backend only provides pre-built Node.js binaries for Node.js LTS 4, 6, 8.

Try e.g. `nvm install 4 && nvm use 4`.

Also this project is a bit outdated and should be updated to the latest node-osrm release:
- https://www.npmjs.com/package/osrm
- https://github.com/mapbox/osrm-isochrone/blob/master/package.json#L5
- https://github.com/mapbox/osrm-isochrone/blob/master/package.json#L30

**Comment by geography** [comment]
Hi Daniel,

after: 
1) nvm install 4 && nvm use 4
2)  sudo npm install -g osrm@^5.0

the results is:

> osrm@5.14.3 install /usr/lib/node_modules/osrm
> node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.14.3/Release/node-v51-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/osrm/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:191:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/usr/lib/node_modules/osrm/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:191:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:411:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Linux 4.4.0-51-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/osrm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /usr/lib/node_modules/osrm
node-pre-gyp ERR! node -v v7.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.14.3/Release/node-v51-linux-x64.tar.gz
/usr/lib/node_modules/osrm/build /usr/lib/node_modules/osrm
CMake Error: The source directory "/usr/lib/node_modules/osrm" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "osrm@^5.0"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! osrm@5.14.3 install: `node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osrm@5.14.3 install script 'node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the osrm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs osrm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls osrm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2018-01-05T11_50_40_757Z-debug.log

**Comment by daniel-j-h** [comment]
> nvm install 4 && nvm use 4
> sudo npm install -g osrm@^5.0

You're still using Node.js 7, check the node-v51 abi tag in your log:

> node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.14.3/Release/node-v51-linux-x64.tar.gz

Probably due to using `sudo` vs non-`sudo` for switching node versions.

**Comment by xiaogu-space** [comment]
Hi,I can't install 
node v6.10.1
npm  v3.10.10

like this:

```
npm WARN deprecated @turf/inside@3.14.0: Module has been renamed to @turf/boolean-point-in-polygon

> osrm@5.18.0 install /Users/xiaogu/Project/dataService/node_modules/osrm
> node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.18.0/Release/node-v48-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/xiaogu/Project/dataService/node_modules/osrm/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:188:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/xiaogu/Project/dataService/node_modules/osrm/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:362:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/xiaogu/Project/dataService/node_modules/osrm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /Users/xiaogu/Project/dataService/node_modules/osrm
node-pre-gyp ERR! node -v v6.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.18.0/Release/node-v48-darwin-x64.tar.gz
Needs cmake to build from source
server@0.0.0 /Users/xiaogu/Project/dataService
└── (empty)

npm WARN Invalid version: "https://registry.npmjs.org/mime-db/-/mime-db-1.30.0.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.11.1.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.11.1.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/mime-db/-/mime-db-1.30.0.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/mime-types/-/mime-types-2.1.17.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/ms/-/ms-0.7.2.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/ms/-/ms-0.7.2.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/negotiator/-/negotiator-0.4.9.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/mime-db/-/mime-db-1.30.0.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/semver/-/semver-5.0.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/bytes/-/bytes-3.0.0.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/semver/-/semver-5.0.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/semver/-/semver-5.0.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/mime-db/-/mime-db-1.30.0.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/semver/-/semver-5.0.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.3.tgz"
npm WARN Invalid version: "https://registry.npmjs.org/mz/-/mz-2.7.0.tgz"
npm ERR! Darwin 17.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! osrm@5.18.0 install: `node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osrm@5.18.0 install script 'node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the osrm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs osrm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls osrm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xiaogu/Project/dataService/npm-debug.log
npm ERR! code 1
```

**Comment by mvl22** [comment]
According to https://github.com/Project-OSRM/osrm-backend/issues/4940#issuecomment-371180588:

"We do not yet support NodeJS 9.x, please downgrade to 8.x LTS."

So switch to Node.js 8:

`nvm install 8 && nvm use 8`

then retry.
