### ISSUE TITLE
Lines are looking skewed

### ISSUE THREAD

**Issue by ramovsky** [mapbox/osrm-isochrone#29]
I'm building the 300 sec polygons around the center of the Berlin
the result is weird [image](http://pix.toile-libre.org/upload/original/1520860497.png)

the second example with the concave polygon is a bit better [image](http://pix.toile-libre.org/upload/original/1520860783.png). But with the hole.

But I don't understand what is the issue with lines and can I trust this polygon then?

**Comment by misotrnka** [comment]
I'm experiencing the same issue. I've basically followed the instructions in README, but I've replaced the `osrm-prepare <mydata.osrm> -p <car.lua>` command with `osrm-contract <mydata.osrm>`. I'm using the sample code from this repo.

As for the OSM data, I've used the `slovakia-lastest.osm` retrieved from [here](url
http://download.geofabrik.de/europe/slovakia-latest.osm.bz2) from Geofabrik.

This is the result (polygon lines highlighted with red arrows):

<img width="276" alt="screen shot 2018-10-26 at 21 47 13" src="https://user-images.githubusercontent.com/2571856/47589477-87ec3d80-d969-11e8-9310-81344aef1ec8.png">
