### ISSUE TITLE
No Data Returned

### ISSUE THREAD

**Issue by Yetzederixx** [mapbox/osrm-isochrone#9]
Firstly I had a problem with the included binaries not producing all the required files, but that is already noted. Using the Louisiana data from Geofabrik (http://download.geofabrik.de/) I was able to generate all required files. 

I copied and pasted your code then changed the file name and coordinates for a nearby business which I received from Google (30.190075, -93.178562). Running the script I get the following output: {"type":"FeatureCollection","features":[]}

Subsequently, I used the osrm-routed server to locate the node:
http://127.0.0.1:5000/locate?loc=30.190075,-93.178562
{"mapped_coordinate":[30.191816,-93.179985],"status":0}

and also the nearest "snapped" node
http://127.0.0.1:5000/nearest?loc=30.190075,-93.178562
{"name":"LA 14","mapped_coordinate":[30.190065,-93.17997],"status":0}

Neither of which worked. I am going to process the entire North America map tonight and try that, but I'm not expecting it to work.

**Comment by TheMarex** [comment]
Make sure to use the binaries distributed with `node-osrm` in `node_modules/osrm/lib/bindings`.

**Comment by nmec** [comment]
I'm getting the same empty `features` response with [GB Data](http://download.geofabrik.de/europe/great-britain.html) and the [walking profile](https://github.com/Project-OSRM/osrm-backend/blob/develop/profiles/foot.lua). 

The data works with `osrm.table` and `osrm.route` methods and dumping out the `response` on [L95](https://github.com/mapbox/osrm-isochrone/blob/master/index.js#L95) shows that is is getting data back, but after going through `this.draw` it is an empty array.

My params:

```js
var time = 600;
var location = [51.61961834,-0.30310817];
var options = {
  resolution: 25,
  maxspeed: 5, 
  network: './data/gb-foot.osrm',
};
```

**Comment by nmec** [comment]
I spent some more time digging in to what was going and found two issues:

1. The location param expects `[lon, lat]` not `[lat, lon]` like elsewhere in OSRM, I'd recommend changing this to be consistent.
2. Some coordinates cause an integer overflow with `osrm.table` so all the times return as `214748365` - this happens even after passing the coords through `osrm.nearest`. I'll see if this is a known issue upstream.

**Comment by TheMarex** [comment]
> recommend changing this to be consistent.

OSRM v5 will be completely `lon,lat`

> 214748365

That is the somewhat badly documented value for `route not found`.

**Comment by nmec** [comment]
Thanks for clearing that up, maybe worth updating the readme so others aren't caught out by `lon,lat`.
